#!/bin/bash

# Prevent direct commits to master branch
BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
if [ "$BRANCH" = "master" ]; then
  echo "Direct commits to master branch are not allowed."
  echo "Please create a branch and submit a pull request instead."
  exit 1
fi


