name: YamsAttackSocket Build

on:
  workflow_run:
    workflows: ['YamsAttackSocket Tests']
    types:
      - completed
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    # Only run if the tests workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build Go application
        run: go build -v ./cmd/server

      # No test steps here since they're now in tests.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yams-attack-socket:latest
